toggling floating centering improvements
Signed-off-by: Kirill kine Nevzorov <akinevz@outlook.com>

diff --git a/herbst/.local/bin/hc_center b/herbst/.local/bin/hc_center
--- a/herbst/.local/bin/hc_center
+++ b/herbst/.local/bin/hc_center
@@ -8,17 +8,22 @@ herb() {
 }
 
 monitor_geom=$(herb attr monitors.focus.geometry)
+win_geom=$(herb attr tags.focus.tiling.focused_frame.content_geometry)
 [[ $monitor_geom =~ ^([0-9]+)x([0-9]+)([+-][0-9]+)([+-][0-9]+)$ ]] || {
-    echo "hc_center: cannot parse geometry '$monitor_geom'" >&2
+    echo "hc_center: cannot parse monitor geometry '$monitor_geom'" >&2
+    exit 1
+}
+[[ $win_geom =~ ^([0-9]+)x([0-9]+)([+-][0-9]+)([+-][0-9]+)$ ]] || {
+    echo "hc_center: cannot parse window geometry '$win_geom'" >&2
     exit 1
 }
 mw=${BASH_REMATCH[1]}
 mh=${BASH_REMATCH[2]}
 mx=${BASH_REMATCH[3]}
 my=${BASH_REMATCH[4]}
-win_w=$((mw * 8 / 10))
-win_h=$((mh * 8 / 10))
+win_w=${BASH_REMATCH[1]}
+win_h=${BASH_REMATCH[2]}
 win_x=$((mx + (mw - win_w) / 2))
 win_y=$((my + (mh - win_h) / 2))
-herb chain . lock . set_attr tags.focus.floating_focused true . set_attr clients.focus.floating_geometry "${win_w}x${win_h}+${win_x}+${win_y}" . unlock
+herb chain . lock . set_attr tags.focus.floating_focused on . set_attr clients.focus.floating_geometry "${win_w}x${win_h}+${win_x}+${win_y}" . unlock
 
